version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: my_app
      POSTGRES_PASSWORD: "1UnpI8LwXQqygHLAfukBJl6ExZJLWJOj"
    volumes:
      - my_app_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "I_0oj1b1z9s9XzYJ2Oq5clXbq9_Z7GrU"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  my_app_data:
